Repository Automattic/Edit-Flow, pull requests merged in 2020-04, with the labels that each got.

#595 Statuses for Story Budget and Calendar should be Edit Flow specific s…
  modules/calendar/calendar.php
  modules/story-budget/story-budget.php
  tests/test-edit-flow-calendar.php
  tests/test-edit-flow-story-budget.php
Labels: [Status] Needs Review

#597 Fix bug preventing previewing posts authored by other users
  modules/custom-status/custom-status.php
Labels: [Status] Ready to Merge, bug

#603 Rewrite calendar filters with React components
  .babelrc
  .babelrc.js
  .prettierrc.js
  .travis.yml
  jest.config.js
  modules/calendar/calendar.php
  modules/calendar/lib/calendar.css
  modules/calendar/lib/dist/calendar.react.build.js
  modules/calendar/lib/dist/calendar.react.style.build.css
  modules/calendar/lib/react/calendar-date-change-buttons/index.js
  modules/calendar/lib/react/calendar-date-change-buttons/style.react.scss
  modules/calendar/lib/react/calendar-filters/index.js
  modules/calendar/lib/react/calendar-filters/style.react.scss
  modules/calendar/lib/react/calendar-header/index.js
  modules/calendar/lib/react/calendar-header/style.react.scss
  modules/calendar/lib/react/calendar.react.js
  modules/calendar/lib/react/combobox/index.js
  modules/calendar/lib/react/combobox/style.react.scss
  package-lock.json
  package.json
  tests/e2e/config/setup-test-framework.js
  tests/e2e/jest.config.js
  tests/e2e/specs/calendar-header.test.js
  tests/e2e/utils/index.js
  tests/jest/calendar/calendar-header.test.js
  tests/jest/calendar/setup.js
  webpack.config.js
Labels: [Status] In-progress, enhancement

#605 Tiny style tweaks to calendar
  modules/calendar/lib/calendar.css
Labels: enhancement
